### ISSUE TITLE
Duplicate parameter error

### ISSUE THREAD

**Issue by nowindxdw** [bigShai/extendify#12]
when we use "extendify" to merge different *.yaml in different folders
we found if we defined one parameter like:
```
  keywords:
    in: query
    name: keywords
    required: false
    type: string
```
and in another place:
```
  keywords:
    in: query
    name: keywords
    required: true
    type: string
```
we see the different "required" cause error in merge yaml.
would you please add some check for duplicate parameters ?
